//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public Nullable<int> DeviceSerial { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> State { get; set; }
        public string UserName { get; set; }
        public string mapX { get; set; }
        public string mapY { get; set; }
    }
}
