// <auto-generated />
namespace TaskShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order));
        
        string IMigrationMetadata.Id
        {
            get { return "201403121046086_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
