// <auto-generated />
namespace TaskShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Price));
        
        string IMigrationMetadata.Id
        {
            get { return "201403142011224_Price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
