// <auto-generated />
namespace TaskShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddBattery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBattery));
        
        string IMigrationMetadata.Id
        {
            get { return "201403141936303_AddBattery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
